all:
	+$(MAKE) -C kap01
	+$(MAKE) -C kap02
	+$(MAKE) -C kap03
	+$(MAKE) -C kap04
	+$(MAKE) -C kap05
	+$(MAKE) -C kap06
	+$(MAKE) -C kap07
	+$(MAKE) -C kap08
	+$(MAKE) -C kap09
	+$(MAKE) -C kap10

	
clean:
	+$(MAKE) -C kap01 clean
	+$(MAKE) -C kap02 clean
	+$(MAKE) -C kap03 clean
	+$(MAKE) -C kap04 clean
	+$(MAKE) -C kap05 clean
	+$(MAKE) -C kap06 clean
	+$(MAKE) -C kap07 clean
	+$(MAKE) -C kap08 clean
	+$(MAKE) -C kap09 clean
	+$(MAKE) -C kap10 clean
