all:
	+$(MAKE) -C b07-01
	+$(MAKE) -C b07-02
	+$(MAKE) -C b07-03
	+$(MAKE) -C b07-04
	+$(MAKE) -C b07-05
	+$(MAKE) -C b07-06
	+$(MAKE) -C b07-07
	+$(MAKE) -C b07-08
	+$(MAKE) -C b07-09
	+$(MAKE) -C b07-10
	+$(MAKE) -C b07-11
	+$(MAKE) -C b07-12	
	+$(MAKE) -C b07-13 
	+$(MAKE) -C b07-14 
	+$(MAKE) -C b07-15 
	+$(MAKE) -C b07-16 


clean:
	+$(MAKE) -C b07-01 clean
	+$(MAKE) -C b07-02 clean
	+$(MAKE) -C b07-03 clean
	+$(MAKE) -C b07-04 clean
	+$(MAKE) -C b07-05 clean
	+$(MAKE) -C b07-06 clean
	+$(MAKE) -C b07-07 clean
	+$(MAKE) -C b07-08 clean
	+$(MAKE) -C b07-09 clean
	+$(MAKE) -C b07-10 clean
	+$(MAKE) -C b07-11 clean
	+$(MAKE) -C b07-12 clean
	+$(MAKE) -C b07-13 clean
	+$(MAKE) -C b07-14 clean
	+$(MAKE) -C b07-15 clean
	+$(MAKE) -C b07-16 clean


