all:
	+$(MAKE) -C b08-01
	+$(MAKE) -C b08-02
	+$(MAKE) -C b08-03
	+$(MAKE) -C b08-04
	+$(MAKE) -C b08-05
	+$(MAKE) -C b08-06
	+$(MAKE) -C b08-07
	+$(MAKE) -C b08-08
	+$(MAKE) -C b08-09
	+$(MAKE) -C b08-10
	+$(MAKE) -C b08-11


clean:
	+$(MAKE) -C b08-01 clean
	+$(MAKE) -C b08-02 clean
	+$(MAKE) -C b08-03 clean
	+$(MAKE) -C b08-04 clean
	+$(MAKE) -C b08-05 clean
	+$(MAKE) -C b08-06 clean
	+$(MAKE) -C b08-07 clean
	+$(MAKE) -C b08-08 clean
	+$(MAKE) -C b08-09 clean
	+$(MAKE) -C b08-10 clean
	+$(MAKE) -C b08-11 clean


