all:
	+$(MAKE) -C b04-01
	+$(MAKE) -C b04-02
	+$(MAKE) -C b04-03
	+$(MAKE) -C b04-04
	+$(MAKE) -C b04-05
	+$(MAKE) -C b04-06
	+$(MAKE) -C b04-07

clean:
	+$(MAKE) -C b04-01 clean
	+$(MAKE) -C b04-02 clean
	+$(MAKE) -C b04-03 clean
	+$(MAKE) -C b04-04 clean
	+$(MAKE) -C b04-05 clean
	+$(MAKE) -C b04-06 clean
	+$(MAKE) -C b04-07 clean

