all:
	+$(MAKE) -C b01-01
	+$(MAKE) -C b01-02
	+$(MAKE) -C b01-03
	+$(MAKE) -C b01-04
	+$(MAKE) -C b01-05
clean:
	+$(MAKE) -C b01-01 clean
	+$(MAKE) -C b01-02 clean
	+$(MAKE) -C b01-03 clean
	+$(MAKE) -C b01-04 clean
	+$(MAKE) -C b01-05 clean
