all:
	+$(MAKE) -C b06-01
	+$(MAKE) -C b06-02
	+$(MAKE) -C b06-03
	+$(MAKE) -C b06-04
	+$(MAKE) -C b06-05
	+$(MAKE) -C b06-06
	+$(MAKE) -C b06-07
	+$(MAKE) -C b06-08
	+$(MAKE) -C b06-09
	+$(MAKE) -C b06-10
	+$(MAKE) -C b06-11
	+$(MAKE) -C b06-12	
	+$(MAKE) -C b06-13 
	+$(MAKE) -C b06-14 
	+$(MAKE) -C b06-15 
	+$(MAKE) -C b06-16 
	+$(MAKE) -C b06-17 

clean:
	+$(MAKE) -C b06-01 clean
	+$(MAKE) -C b06-02 clean
	+$(MAKE) -C b06-03 clean
	+$(MAKE) -C b06-04 clean
	+$(MAKE) -C b06-05 clean
	+$(MAKE) -C b06-06 clean
	+$(MAKE) -C b06-07 clean
	+$(MAKE) -C b06-08 clean
	+$(MAKE) -C b06-09 clean
	+$(MAKE) -C b06-10 clean
	+$(MAKE) -C b06-11 clean
	+$(MAKE) -C b06-12 clean
	+$(MAKE) -C b06-13 clean
	+$(MAKE) -C b06-14 clean
	+$(MAKE) -C b06-15 clean
	+$(MAKE) -C b06-16 clean
	+$(MAKE) -C b06-17 clean


