all:
	+$(MAKE) -C b05-01
	+$(MAKE) -C b05-02
	+$(MAKE) -C b05-03
	+$(MAKE) -C b05-04
	+$(MAKE) -C b05-05
	+$(MAKE) -C b05-06
	+$(MAKE) -C b05-07

clean:
	+$(MAKE) -C b05-01 clean
	+$(MAKE) -C b05-02 clean
	+$(MAKE) -C b05-03 clean
	+$(MAKE) -C b05-04 clean
	+$(MAKE) -C b05-05 clean
	+$(MAKE) -C b05-06 clean
	+$(MAKE) -C b05-07 clean
