all:
	+$(MAKE) -C b03-01
	+$(MAKE) -C b03-02
	+$(MAKE) -C b03-03
	+$(MAKE) -C b03-04
	+$(MAKE) -C b03-05
	+$(MAKE) -C b03-06
	+$(MAKE) -C b03-07
	+$(MAKE) -C b03-08
	+$(MAKE) -C b03-09
	+$(MAKE) -C b03-10
#	+$(MAKE) -C b03-11
#	+$(MAKE) -C b03-12	
clean:
	+$(MAKE) -C b03-01 clean
	+$(MAKE) -C b03-02 clean
	+$(MAKE) -C b03-03 clean
	+$(MAKE) -C b03-04 clean
	+$(MAKE) -C b03-05 clean
	+$(MAKE) -C b03-06 clean
	+$(MAKE) -C b03-07 clean
	+$(MAKE) -C b03-08 clean
	+$(MAKE) -C b03-09 clean
	+$(MAKE) -C b03-10 clean
#	+$(MAKE) -C b03-11 clean
#	+$(MAKE) -C b03-12 clean
#	+$(MAKE) -C b03-13 clean
#	+$(MAKE) -C b03-14 clean
#	+$(MAKE) -C b03-15 clean
#	+$(MAKE) -C b03-16 clean
#	+$(MAKE) -C b03-17 clean
#	+$(MAKE) -C b03-18 clean

