all:
	+$(MAKE) -C b10-01
	+$(MAKE) -C b10-02
	+$(MAKE) -C b10-03
	+$(MAKE) -C b10-04
	+$(MAKE) -C b10-05
	+$(MAKE) -C b10-06
	+$(MAKE) -C b10-07
	+$(MAKE) -C b10-08
	+$(MAKE) -C b10-09
	+$(MAKE) -C b10-10
	+$(MAKE) -C b10-11
	+$(MAKE) -C b10-12	
	+$(MAKE) -C b10-13 
	+$(MAKE) -C b10-14 
	+$(MAKE) -C b10-15 
	+$(MAKE) -C b10-16 
	+$(MAKE) -C b10-17 
	+$(MAKE) -C b10-18
	+$(MAKE) -C b10-19
	+$(MAKE) -C b10-20
	+$(MAKE) -C b10-21
	+$(MAKE) -C b10-22 

clean:
	+$(MAKE) -C b10-01 clean
	+$(MAKE) -C b10-02 clean
	+$(MAKE) -C b10-03 clean
	+$(MAKE) -C b10-04 clean
	+$(MAKE) -C b10-05 clean
	+$(MAKE) -C b10-06 clean
	+$(MAKE) -C b10-07 clean
	+$(MAKE) -C b10-08 clean
	+$(MAKE) -C b10-09 clean
	+$(MAKE) -C b10-10 clean
	+$(MAKE) -C b10-11 clean
	+$(MAKE) -C b10-12 clean
	+$(MAKE) -C b10-13 clean
	+$(MAKE) -C b10-14 clean
	+$(MAKE) -C b10-15 clean
	+$(MAKE) -C b10-16 clean
	+$(MAKE) -C b10-17 clean
	+$(MAKE) -C b10-18 clean
	+$(MAKE) -C b10-19 clean
	+$(MAKE) -C b10-20 clean
	+$(MAKE) -C b10-21 clean
	+$(MAKE) -C b10-22 clean
