all:
	+$(MAKE) -C b09-01
	+$(MAKE) -C b09-02
	+$(MAKE) -C b09-03
	+$(MAKE) -C b09-04
	+$(MAKE) -C b09-05
	+$(MAKE) -C b09-06
	+$(MAKE) -C b09-07


clean:
	+$(MAKE) -C b09-01 clean
	+$(MAKE) -C b09-02 clean
	+$(MAKE) -C b09-03 clean
	+$(MAKE) -C b09-04 clean
	+$(MAKE) -C b09-05 clean
	+$(MAKE) -C b09-06 clean
	+$(MAKE) -C b09-07 clean


